spring.jackson.serialization.INDENT_OUTPUT: true
#LOGGING
logging:
  #Deshabilitaremos los logs, en caso de depurar descomentarlo
  #file: "c:/script/logs/script.log"
  level:
    root: ERROR
    org.springframework.web: DEBUG
    dgip.sgcp.ipp.core: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG

#Server port
server:
    port: 8082
    servlet:
    #Seteamos el contexto para llamarlo http://localhost:8082/seido/xxxx
      context-path: /seido/

spring:
  application:
    name: gitLab-service-api
  profiles:
    #http://localhost:8082/seido/swagger-ui.html
    active: swagger
  cloud:
    config:
      enabled: true
  logging:
    level:
      ROOT: DEBUG
      com.seido.micro.core: DEBUG
      org.hibernate: WARN
      #type: trace

github:
  api:
    owner:
    token:


